### ISSUE TITLE
Squared Euclidean not metric

### ISSUE THREAD

**Issue by Dobatymo** [pablocael/pyvptree#1]
Hi, great library!

But I think it’s incorrect to use the squared Euclidean optimization since vp trees require a real metric which I think the squared distance is not.

**Comment by Dobatymo** [comment]
I just made the bulids a bit simpler and also made it compile on windows.
https://github.com/pablocael/pyvptree/compare/main...Dobatymo:pyvptree:windows-compat?expand=1
Let me know if there's anything I can do to help.

**Comment by pablocael** [comment]
Fixed on #8
